apiVersion: v1
kind: Service

metadata:
  name: jsluxe-service

spec:
  selector:
    app: jsluxe-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

  type: NodePort
