apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsluxe-app
  labels:
    app: jsluxe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsluxe-app
  template:
    metadata:
      labels:
        app: jsluxe-app
    spec:
      containers:
        - name: jsluxe-app
          image: muthuphy33/jsluxe-app:b6794f31dcd0a1060dc294407efc1f56f56339e7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
