apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsluxe-app
  labels:
    app: jsluxe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsluxe-app
  template:
    metadata:
      labels:
        app: jsluxe-app
    spec:
      containers:
        - name: jsluxe-app
          image: muthuphy33/jsluxe-app:d4ee18d2290c0d96f928835c8b9a9d6d6f658088
          imagePullPolicy: Always
          ports:
            - containerPort: 80
