apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsluxe-app
  labels:
    app: jsluxe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsluxe-app
  template:
    metadata:
      labels:
        app: jsluxe-app
    spec:
      containers:
        - name: jsluxe-app
          image: muthuphy33/jsluxe-app:860411b80d8928a5d871ede5c36010f5afde954f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
