apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsluxe-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: jsluxe.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jsluxe-service
            port:
              number: 80
